"""orders added

Revision ID: fec8b436f644
Revises: 
Create Date: 2024-07-27 22:22:22.587511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec8b436f644'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_Product_product_id'), 'Product', ['product_id'], unique=True)
    op.create_table('Users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number_prefix', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_merchant', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_Users_address'), 'Users', ['address'], unique=False)
    op.create_index(op.f('ix_Users_email'), 'Users', ['email'], unique=True)
    op.create_index(op.f('ix_Users_firebase_uid'), 'Users', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_Users_name'), 'Users', ['name'], unique=False)
    op.create_index(op.f('ix_Users_phone_number'), 'Users', ['phone_number'], unique=False)
    op.create_index(op.f('ix_Users_user_id'), 'Users', ['user_id'], unique=True)
    op.create_table('Merchants',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('delivery_fee', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('merchant_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_Merchants_address'), 'Merchants', ['address'], unique=False)
    op.create_index(op.f('ix_Merchants_email'), 'Merchants', ['email'], unique=True)
    op.create_index(op.f('ix_Merchants_merchant_id'), 'Merchants', ['merchant_id'], unique=True)
    op.create_table('Customer_Orders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_order_placed', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('total_order_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['Merchants.merchant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Customer_Orders_order_id'), 'Customer_Orders', ['order_id'], unique=True)
    op.create_index(op.f('ix_Customer_Orders_reference_no'), 'Customer_Orders', ['reference_no'], unique=True)
    op.create_index(op.f('ix_Customer_Orders_status'), 'Customer_Orders', ['status'], unique=False)
    op.create_table('Customer_Orders_Items',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['Product.product_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['Customer_Orders.order_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_Customer_Orders_Items_order_id'), 'Customer_Orders_Items', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Customer_Orders_Items_order_id'), table_name='Customer_Orders_Items')
    op.drop_table('Customer_Orders_Items')
    op.drop_index(op.f('ix_Customer_Orders_status'), table_name='Customer_Orders')
    op.drop_index(op.f('ix_Customer_Orders_reference_no'), table_name='Customer_Orders')
    op.drop_index(op.f('ix_Customer_Orders_order_id'), table_name='Customer_Orders')
    op.drop_table('Customer_Orders')
    op.drop_index(op.f('ix_Merchants_merchant_id'), table_name='Merchants')
    op.drop_index(op.f('ix_Merchants_email'), table_name='Merchants')
    op.drop_index(op.f('ix_Merchants_address'), table_name='Merchants')
    op.drop_table('Merchants')
    op.drop_index(op.f('ix_Users_user_id'), table_name='Users')
    op.drop_index(op.f('ix_Users_phone_number'), table_name='Users')
    op.drop_index(op.f('ix_Users_name'), table_name='Users')
    op.drop_index(op.f('ix_Users_firebase_uid'), table_name='Users')
    op.drop_index(op.f('ix_Users_email'), table_name='Users')
    op.drop_index(op.f('ix_Users_address'), table_name='Users')
    op.drop_table('Users')
    op.drop_index(op.f('ix_Product_product_id'), table_name='Product')
    op.drop_table('Product')
    # ### end Alembic commands ###
