"""orders added

Revision ID: fec8b436f644
Revises: 
Create Date: 2024-07-27 22:22:22.587511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec8b436f644'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_product_product_id'), 'product', ['product_id'], unique=True)
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('phone_number_prefix', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('is_merchant', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_phone_number'), 'user', ['phone_number'], unique=False)
    op.create_index(op.f('ix_user_user_id'), 'user', ['user_id'], unique=True)
    op.create_table('merchant',
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('delivery_fee', sa.Float(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('merchant_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_merchant_address'), 'merchant', ['address'], unique=False)
    op.create_index(op.f('ix_merchant_email'), 'merchant', ['email'], unique=True)
    op.create_index(op.f('ix_merchant_merchant_id'), 'merchant', ['merchant_id'], unique=True)
    op.create_table('customer_order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reference_no', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('date_order_placed', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('merchant_id', sa.Integer(), nullable=True),
    sa.Column('total_order_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.merchant_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_customer_order_order_id'), 'customer_order', ['order_id'], unique=True)
    op.create_index(op.f('ix_customer_order_reference_no'), 'customer_order', ['reference_no'], unique=True)
    op.create_index(op.f('ix_customer_order_status'), 'customer_order', ['status'], unique=False)
    op.create_table('customer_order_item',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['product.product_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['customer_order.order_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_index(op.f('ix_customer_order_item_order_id'), 'customer_order_item', ['order_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_order_item_order_id'), table_name='customer_order_item')
    op.drop_table('customer_order_item')
    op.drop_index(op.f('ix_customer_order_status'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_reference_no'), table_name='customer_order')
    op.drop_index(op.f('ix_customer_order_order_id'), table_name='customer_order')
    op.drop_table('customer_order')
    op.drop_index(op.f('ix_merchant_merchant_id'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_email'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_address'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_user_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_phone_number'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_product_product_id'), table_name='product')
    op.drop_table('product')
    # ### end Alembic commands ###